/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Confession as PrismaConfession } from "@prisma/client";

export class ConfessionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ConfessionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.confession.count(args);
  }

  async confessions(
    args: Prisma.ConfessionFindManyArgs
  ): Promise<PrismaConfession[]> {
    return this.prisma.confession.findMany(args);
  }
  async confession(
    args: Prisma.ConfessionFindUniqueArgs
  ): Promise<PrismaConfession | null> {
    return this.prisma.confession.findUnique(args);
  }
  async createConfession(
    args: Prisma.ConfessionCreateArgs
  ): Promise<PrismaConfession> {
    return this.prisma.confession.create(args);
  }
  async updateConfession(
    args: Prisma.ConfessionUpdateArgs
  ): Promise<PrismaConfession> {
    return this.prisma.confession.update(args);
  }
  async deleteConfession(
    args: Prisma.ConfessionDeleteArgs
  ): Promise<PrismaConfession> {
    return this.prisma.confession.delete(args);
  }
}
